# Generated by Django 3.2.9 on 2022-01-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milaboratorio', '0002_alter_solucion_problema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucion',
            name='link_gist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='texto_solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
